# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-01 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='Codigo', max_length=10)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('uf', models.CharField(db_column='Uf', max_length=2)),
            ],
            options={
                'db_table': 'bairro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('idendereco', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'endereco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('codigouf', models.IntegerField(db_column='CodigoUf')),
                ('nome', models.CharField(db_column='Nome', max_length=50)),
                ('uf', models.CharField(db_column='Uf', max_length=2)),
                ('regiao', models.IntegerField(db_column='regiao')),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idevento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
                ('quantidade_gente_min', models.IntegerField(blank=True, null=True)),
                ('quantidade_gente_max', models.IntegerField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=45, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('horario_chegada', models.TimeField(blank=True, null=True)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fim', models.TimeField(blank=True, null=True)),
                ('tempo_espera_max', models.FloatField(blank=True, null=True)),
                ('banner_link', models.CharField(blank=True, max_length=45, null=True, unique=True)),
            ],
            options={
                'db_table': 'evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventoHasRegra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'evento_has_regra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventoLista',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
                ('lista_level', models.IntegerField()),
                ('item_level', models.IntegerField()),
            ],
            options={
                'db_table': 'evento_lista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventoListaItem',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
                ('quantidade_desejada_min', models.IntegerField()),
            ],
            options={
                'db_table': 'evento_lista_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventoListaTipo',
            fields=[
                ('idevento_lista_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=45, unique=True)),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'evento_lista_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventoOrganizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
            ],
            options={
                'db_table': 'evento_organizacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventoParticipante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'evento_participante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventoRegra',
            fields=[
                ('idevento_regra', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=45, unique=True)),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'evento_regra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventoTipo',
            fields=[
                ('idevento_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=45, unique=True)),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'evento_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPorPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'db_table': 'item_por_pessoa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(db_column='Codigo')),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('uf', models.CharField(db_column='Uf', max_length=2)),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoCondicao',
            fields=[
                ('idparticipacao_condicao', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=45, unique=True)),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'participacao_condicao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoStatus',
            fields=[
                ('idparticipacao_status', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=45, unique=True)),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'participacao_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipanteHasCondicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'participante_has_condicao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('idpessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('sobrenome', models.CharField(max_length=45)),
                ('nickname', models.CharField(blank=True, max_length=45, null=True)),
                ('data_nascimento', models.DateField()),
                ('email', models.CharField(max_length=45, unique=True)),
                ('retrato_link', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'pessoa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaAmizade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'pessoa_amizade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaGeneroSexual',
            fields=[
                ('idpessoa_genero_sexual', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=45, unique=True)),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'pessoa_genero_sexual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=50)),
            ],
            options={
                'db_table': 'regiao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoHasRegra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tipo_has_regra',
                'managed': False,
            },
        ),
    ]
